CREATE TABLE IF NOT EXISTS courses (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `courseNumber` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `status` ENUM('open', 'closed') NOT NULL,
  `lastChecked` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY (courseNumber)
);