spring:
    datasource:
        hikari:
            jdbc-url: ${SPRING_DATASOURCE_URL}
            username: ${SPRING_DATASOURCE_USERNAME}
            password: ${SPRING_DATASOURCE_PASSWORD}
            maximum-pool-size: 30
            driver-class-name: com.mysql.cj.jdbc.Driver
    application:
        name: backend
    config:
        import: optional:file:.env[.properties]
server:
    error:
      include-binding-errors: always
      include-message: always
    port: 8080