spring:
    datasource:
        hikari:
            jdbc-url: jdbc:mysql://localhost:3306/scarlet_sniper
            username: "root"
            password: "password"
            maximum-pool-size: 30
            driver-class-name: com.mysql.cj.jdbc.Driver
    application:
        name: backend
server:
    error:
      include-binding-errors: always
      include-message: always
    port: 8080